# -*- mode: python ; coding: utf-8 -*-
"""Agent Notify PyInstaller 打包配置"""

import os

base_dir = os.path.dirname(os.path.abspath(SPEC))

a = Analysis(
    [os.path.join(base_dir, 'main.py')],
    pathex=[base_dir],
    binaries=[],
    datas=[
        (os.path.join(base_dir, 'resources'), 'resources'),
        (os.path.join(base_dir, 'hooks', 'claude_hook.py'), 'hooks'),
        (os.path.join(base_dir, 'aider_notify_helper.py'), '.'),
    ],
    hiddenimports=[
        'PySide6.QtWidgets',
        'PySide6.QtGui',
        'PySide6.QtCore',
        'PySide6.QtSvg',
        'PySide6.QtMultimedia',
        'events',
        'event_bus',
        'updater',
        'autostart',
        'adapters',
        'adapters.base',
        'adapters.registry',
        'adapters.signal_file',
        'adapters.claude_code',
        'adapters.cursor',
        'adapters.aider',
        'adapters.custom',
        'adapters.windsurf',
        'ui',
        'ui.widgets',
        'ui.settings',
        'ui.tray',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'PySide6.QtWebEngineCore',
        'PySide6.QtWebEngineWidgets',
        'PySide6.QtWebEngineQuick',
        'PySide6.Qt3DCore',
        'PySide6.Qt3DRender',
        'PySide6.Qt3DInput',
        'PySide6.Qt3DLogic',
        'PySide6.Qt3DExtras',
        'PySide6.Qt3DAnimation',
        'PySide6.QtBluetooth',
        'PySide6.QtNfc',
        'PySide6.QtPositioning',
        'PySide6.QtQuick',
        'PySide6.QtQuickWidgets',
        'PySide6.QtQml',
        'PySide6.QtDesigner',
        'PySide6.QtHelp',
        'PySide6.QtShaderTools',
        'PySide6.QtSpatialAudio',
        'PySide6.QtTest',
        'PySide6.QtUiTools',
        'numpy',
        'pandas',
        'matplotlib',
        'scipy',
        'PIL',
        'cv2',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='AgentNotify',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=os.path.join(base_dir, 'resources', 'icon.ico') if os.path.exists(os.path.join(base_dir, 'resources', 'icon.ico')) else None,
)
